import simpleGit from 'simple-git'
import { createDraftPR, findOpenPRsByHeadPattern } from '@/lib/github'
import type { FilePatch } from '@/lib/agent/patching/full-file'
import type { BreakingChange } from '@/lib/agent/signals/changelog'
import type { Diagnosis } from './diagnose'
import type { StaleDep } from './detect'

// ─── Branch naming ────────────────────────────────────────────────────────────

function depSlug(name: string): string {
  return name.replace(/[@/]/g, '-').replace(/[^a-z0-9-]/gi, '').replace(/-+/g, '-')
}

function makeBranchName(dep: StaleDep): string {
  const nonce = Math.random().toString(16).slice(2, 6)
  return `mendel/deps/${depSlug(dep.name)}-${Date.now()}-${nonce}`
}

// ─── PR body ─────────────────────────────────────────────────────────────────

function buildPRBody(
  dep: StaleDep,
  breakingChanges: BreakingChange[],
  diagnosis: Diagnosis,
  patches: FilePatch[],
  verificationPassed: boolean,
): string {
  const evidenceLines =
    breakingChanges.length > 0
      ? breakingChanges
          .slice(0, 5)
          .map((bc) => `- [${bc.symbol} (${bc.changeType})](${bc.sourceUrl}): ${bc.description}`)
          .join('\n')
      : `- Significant version gap: ${dep.currentVersion} → ${dep.latestVersion} (major bump)`

  const changesLines = patches
    .map((p) => `- \`${p.filePath}\`: ${p.explanation}`)
    .join('\n')

  const verifyLine = verificationPassed
    ? '- ✅ TypeScript check passed in isolated Docker sandbox (--network=none)'
    : '- ⚠️ Verification incomplete — review the diff carefully before merging'

  return `## What
Upgrades \`${dep.name}\` from \`${dep.currentVersion}\` to \`${dep.latestVersion}\`.

## Why
${diagnosis.impact}

## ⚠️ Confidence: medium — manual review required
This PR was generated by an autonomous agent using changelog parsing only.
Please review carefully before marking ready or merging.

## Evidence
${evidenceLines}

## Changes
${changesLines}

## Verification Results
${verifyLine}

## ⚠ Not Analyzed
- Full runtime behavior: changelog-parsing-only analysis. Semantic API diffing not available in v1.0.

Analysis coverage: changelog-parsing-only.

---
*Generated by Mendel v1.0. Open as Draft — mark ready for review when you've validated.*`
}

// ─── Types ───────────────────────────────────────────────────────────────────

export type PRSubmitResult = {
  prUrl: string
  branchName: string
  skipped: boolean
  skipReason?: string
}

// ─── Public API ──────────────────────────────────────────────────────────────

export async function submitDraftPR(
  repoPath: string,
  owner: string,
  repo: string,
  defaultBranch: string,
  dep: StaleDep,
  breakingChanges: BreakingChange[],
  diagnosis: Diagnosis,
  patches: FilePatch[],
  verificationPassed: boolean,
  pat: string,
  emit: (msg: string) => void,
): Promise<PRSubmitResult> {
  // Dedup: check for existing open Mendel PRs for this dep
  const headPattern = `mendel/deps/${depSlug(dep.name)}`
  const existing = await findOpenPRsByHeadPattern(pat, owner, repo, headPattern)
  if (existing.length > 0) {
    emit(`  Existing PR found: ${existing[0].url}`)
    return { prUrl: existing[0].url, branchName: existing[0].headRef, skipped: true, skipReason: 'duplicate' }
  }

  const branchName = makeBranchName(dep)

  // Configure git with PAT in remote URL for push auth
  const git = simpleGit(repoPath)
  const authRemote = `https://${pat}@github.com/${owner}/${repo}.git`
  await git.remote(['set-url', 'origin', authRemote])

  emit(`Creating branch ${branchName}...`)
  await git.checkoutLocalBranch(branchName)
  await git.add('.')
  await git.commit(
    `fix(deps): upgrade ${dep.name} from ${dep.currentVersion} to ${dep.latestVersion}\n\nCo-authored-by: Mendel <mendel@bot.local>`,
  )

  emit('Pushing branch...')
  await git.push('origin', branchName)

  // Reset remote URL to non-authenticated form
  await git.remote(['set-url', 'origin', `https://github.com/${owner}/${repo}.git`])

  emit('Opening Draft PR...')
  const body = buildPRBody(dep, breakingChanges, diagnosis, patches, verificationPassed)
  const prUrl = await createDraftPR(pat, owner, repo, {
    title: `fix(deps): upgrade ${dep.name} ${dep.currentVersion} → ${dep.latestVersion}`,
    body,
    head: branchName,
    base: defaultBranch,
  })

  emit(`Draft PR opened: ${prUrl}`)
  return { prUrl, branchName, skipped: false }
}
