import simpleGit from 'simple-git'
import { createDraftPR, findOpenPRsByHeadPattern, canPushToRepo, ensureFork } from '@/lib/github'
import type { FilePatch } from '@/lib/agent/patching/full-file'
import type { BreakingChange } from '@/lib/agent/signals/changelog'
import type { Diagnosis } from './diagnose'
import type { StaleDep } from './detect'
import type { ConfidenceScore } from '@/lib/agent/confidence/score'
import type { SubmissionMode } from '@/lib/agent/confidence/threshold'

// ─── Branch naming ────────────────────────────────────────────────────────────

function depSlug(name: string): string {
  return name.replace(/[@/]/g, '-').replace(/[^a-z0-9-]/gi, '').replace(/-+/g, '-')
}

function makeBranchName(dep: StaleDep): string {
  const nonce = Math.random().toString(16).slice(2, 6)
  return `mendel/deps/${depSlug(dep.name)}-${Date.now()}-${nonce}`
}

// ─── PR body ─────────────────────────────────────────────────────────────────

function buildPRBody(
  dep: StaleDep,
  breakingChanges: BreakingChange[],
  diagnosis: Diagnosis,
  patches: FilePatch[],
  verificationPassed: boolean,
  confidenceScore: ConfidenceScore | null,
  mode: SubmissionMode,
  /** §5c.2 — reference to an existing maintainer-opened issue this PR resolves. */
  issueReference?: string,
): string {
  const evidenceLines =
    breakingChanges.length > 0
      ? breakingChanges
          .slice(0, 5)
          .map((bc) => `- [${bc.symbol} (${bc.changeType})](${bc.sourceUrl}): ${bc.description}`)
          .join('\n')
      : `- Significant version gap: ${dep.currentVersion} → ${dep.latestVersion} (major bump)`

  const changesLines = patches
    .map((p) => `- \`${p.filePath}\`: ${p.explanation}`)
    .join('\n')

  const verifyLine = verificationPassed
    ? '- ✅ TypeScript check passed in isolated Docker sandbox (--network=none)'
    : '- ⚠️ Verification incomplete — review the diff carefully before merging'

  // v1.5 §5b: replace the v1.0 fixed "medium" line with the real calibrated
  // score. When we only have the v1.0 stub (confidenceScore null), preserve
  // the v1.0 framing for back-compat — never silently inflate.
  const confidenceBlock = confidenceScore
    ? buildV15ConfidenceBlock(confidenceScore, mode)
    : `## ⚠️ Confidence: medium — manual review required
This PR was generated by an autonomous agent using changelog parsing only.
Please review carefully before marking ready or merging.`

  const notAnalyzedLines = confidenceScore && confidenceScore.analysisCoverage.percentCovered > 0
    ? `- Analyzed ${confidenceScore.analysisCoverage.percentCovered}% of exported symbols via \`${confidenceScore.analysisCoverage.analysisTier}\` semantic-diff signal.
- Transitive dependency impact of the version bump.
- Test coverage of the changed code paths.`
    : `- Full runtime behavior: changelog-parsing-only analysis. Semantic API diffing not available.`

  const footer = mode === 'standard'
    ? '*Generated by Mendel v1.5. Confidence above your threshold — opened as a standard PR.*'
    : '*Generated by Mendel v1.5. Open as Draft — mark ready for review when you have validated.*'

  const issueLine = issueReference ? `${issueReference}\n\n` : ''

  return `${issueLine}## What
Upgrades \`${dep.name}\` from \`${dep.currentVersion}\` to \`${dep.latestVersion}\`.

## Why
${diagnosis.impact}

${confidenceBlock}

## Evidence
${evidenceLines}

## Changes
${changesLines}

## Verification Results
${verifyLine}

## ⚠ Not Analyzed
${notAnalyzedLines}

---
${footer}`
}

/** v1.5 confidence block — surfaces the calibrated score + bucket + per-symbol tags. */
function buildV15ConfidenceBlock(score: ConfidenceScore, mode: SubmissionMode): string {
  const bucketEmoji = score.bucket === 'high' ? '🟢' : score.bucket === 'medium' ? '🟡' : '🔴'
  const tagLines = score.perBreakingChange
    .filter((p) => p.tag)
    .slice(0, 8)
    .map((p) => `- \`${p.symbol}\` — ${p.score}/100 · ${p.tag}`)
    .join('\n')
  const tagBlock = tagLines ? `\n\nPer-symbol breakdown:\n${tagLines}` : ''
  const cap = score.verificationCapped
    ? '\n\n⚠️ Overall score was capped at 50 because verification did not pass — extra caution warranted.'
    : ''
  const modeNote = mode === 'draft'
    ? '\n\nOpened as **Draft** because the score is below your configured threshold — please review and mark ready when validated.'
    : ''
  return `## ${bucketEmoji} Confidence: ${score.overall}/100 (${score.bucket}) — calibrated
Signals: changelog parsing + semantic API diffing (\`${score.analysisCoverage.analysisTier}\`, ${score.analysisCoverage.percentCovered}% coverage)${cap}${modeNote}${tagBlock}`
}

// ─── Types ───────────────────────────────────────────────────────────────────

export type PRSubmitResult = {
  prUrl: string
  branchName: string
  skipped: boolean
  skipReason?: string
}

// ─── Public API ──────────────────────────────────────────────────────────────

export async function submitDraftPR(
  repoPath: string,
  owner: string,
  repo: string,
  defaultBranch: string,
  dep: StaleDep,
  breakingChanges: BreakingChange[],
  diagnosis: Diagnosis,
  patches: FilePatch[],
  verificationPassed: boolean,
  pat: string,
  emit: (msg: string) => void,
  /** v1.5 Workstream #2 — calibrated score for body rendering. Null = use v1.0 framing. */
  confidenceScore: ConfidenceScore | null = null,
  /** v1.5 Workstream #3 — submission mode chosen by the threshold gate.
   *  'standard' = non-Draft, 'draft' = Draft with warning. 'skip' is enforced
   *  by the caller (runner) before this function is invoked. */
  mode: SubmissionMode = 'draft',
  /** §5c.2 — pre-formatted reference to a maintainer-opened issue (e.g. "Addresses #98 — …"). */
  issueReference?: string,
): Promise<PRSubmitResult> {
  if (mode === 'skip') {
    // Defensive: runner should never call us in skip mode.
    throw new Error('submitDraftPR called with mode=skip — runner must filter before submit')
  }

  // Dedup: check for existing open Mendel PRs for this dep
  const headPattern = `mendel/deps/${depSlug(dep.name)}`
  const existing = await findOpenPRsByHeadPattern(pat, owner, repo, headPattern)
  if (existing.length > 0) {
    emit(`  Existing PR found: ${existing[0].url}`)
    return { prUrl: existing[0].url, branchName: existing[0].headRef, skipped: true, skipReason: 'duplicate' }
  }

  const branchName = makeBranchName(dep)

  // Decide where to PUSH the branch. We can only push to a repo we have write
  // access to. For repos the user doesn't own (the common OSS case), pushing to
  // upstream 403s — so fork into the user's account, push to the fork, and open
  // the PR fork→upstream. The PR itself is ALWAYS created on the upstream repo
  // (owner/repo) so it shows as a contribution there; only the head differs.
  let pushOwner = owner
  let pushRepo = repo
  let prHead = branchName // cross-repo PRs use `forkOwner:branch`
  const hasWriteAccess = await canPushToRepo(pat, owner, repo)
  if (!hasWriteAccess) {
    emit(`No write access to ${owner}/${repo} — forking into your account...`)
    const fork = await ensureFork(pat, owner, repo)
    pushOwner = fork.owner
    pushRepo = fork.repo
    prHead = `${fork.owner}:${branchName}`
    emit(`Fork ready: ${fork.owner}/${fork.repo}`)
  }

  // Configure git with PAT in the push-target remote URL for auth
  const git = simpleGit(repoPath)
  const authRemote = `https://${pat}@github.com/${pushOwner}/${pushRepo}.git`
  await git.remote(['set-url', 'origin', authRemote])

  emit(`Creating branch ${branchName}...`)
  await git.checkoutLocalBranch(branchName)
  await git.add('.')
  await git.commit(
    `fix(deps): upgrade ${dep.name} from ${dep.currentVersion} to ${dep.latestVersion}\n\nCo-authored-by: Mendel <mendel@bot.local>`,
  )

  emit(hasWriteAccess ? 'Pushing branch...' : 'Pushing branch to fork...')
  await git.push('origin', branchName)

  // Reset remote URL to the non-authenticated push target
  await git.remote(['set-url', 'origin', `https://github.com/${pushOwner}/${pushRepo}.git`])

  const isDraft = mode === 'draft'
  emit(isDraft ? 'Opening Draft PR...' : 'Opening standard PR (score above threshold)...')
  const body = buildPRBody(dep, breakingChanges, diagnosis, patches, verificationPassed, confidenceScore, mode, issueReference)
  // PR is created on the UPSTREAM repo (owner/repo); head may be `forkOwner:branch`.
  const prUrl = await createDraftPR(pat, owner, repo, {
    title: `fix(deps): upgrade ${dep.name} ${dep.currentVersion} → ${dep.latestVersion}`,
    body,
    head: prHead,
    base: defaultBranch,
    draft: isDraft,
  })

  emit(`${isDraft ? 'Draft PR' : 'Standard PR'} opened: ${prUrl}`)
  return { prUrl, branchName, skipped: false }
}

/* ── Test-only export — surface the body builder so tests can assert content ── */
export const __testing = { buildPRBody, buildV15ConfidenceBlock }
